pub mod command_fn_pointers;
pub mod command_migration_traits;
pub mod command_trait_objects;
pub mod interpreter;
pub mod interpreter_euclidean_length;
pub mod new_type;
pub mod raii_guards;
pub mod strategy_aka_ioc;
pub mod strategy_closures;
